spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:HibernateDB
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true


springdoc:
    security:
        enabled: false
    swagger-ui:
        path: '/swagger-ui.html'
    api-docs:
        path: '/api-docs'
    baseUrl:
        local: 'http://localhost:8080'
        prod: 'https://bezkoder-api.com'

management:
    endpoints.web.exposure.include: openapi, swagger-ui