spring:
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:HibernateDB
        username: sa
        password: ''
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                id:
                    new_generator_mappings: false
                show_sql: true
